package root:ic-sig-verifier;

world ic-sig-verifier {
  export verify-canister-sig: func(args-serialized: list<u8>) -> list<u8>;
  export verify-bls-sig: func(args-serialized: list<u8>) -> list<u8>;
}
