package motoko:component;

world motoko {
  import ic-sig-verifier: interface {
    verify-bls-sig: func(args-serialized: list<u8>) -> list<u8>;
    verify-canister-sig: func(args-serialized: list<u8>) -> list<u8>;
  }
  import meet-and-greet: interface {
    say-goodbye: func(guest-name: list<u8>) -> list<u8>;
    say-hello: func(guest-name: list<u8>) -> list<u8>;
  }
}
