package component:meet-and-greet;

world meet-and-greet {
  export say-hello: func(guest-name: list<u8>) -> list<u8>;
  export say-goodbye: func(guest-name: list<u8>) -> list<u8>;
  export concat0: func() -> list<u8>;
  export concat2: func(a: list<u8>, b: list<u8>) -> list<u8>;

  export prim-bool: func(a: bool) -> bool;
  export prim-char: func(a: char) -> char;
  export prim-u8: func(a: u8) -> u8;
  export prim-u16: func(a: u16) -> u16;
  export prim-u32: func(a: u32) -> u32;
  export prim-u64: func(a: u64) -> u64;
  export prim-i8: func(a: s8) -> s8;
  export prim-i16: func(a: s16) -> s16;
  export prim-i32: func(a: s32) -> s32;
  export prim-i64: func(a: s64) -> s64;
  export prim-f64: func(a: f64) -> f64;
  export prim-string: func(a: string) -> string;

  export vec-u16: func(a: list<u16>) -> string;
  export vec-string: func(a: list<string>) -> string;
  export vec-u8: func(a: list<u8>) -> string;
  export vec-u32: func(a: list<u32>) -> string;
  export vec-i32: func(a: list<s32>) -> string;
  export vec-i64: func(a: list<s64>) -> string;
  export vec-bool: func(a: list<bool>) -> string;
  export vec-string-nested: func(a: list<list<string>>) -> string;
  export vec-char: func(a: list<char>) -> string;
  export vec-f64: func(a: list<f64>) -> string;
}
